# Generated by Django 5.1.6 on 2025-02-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('ingredients', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('owner_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Десерты', 'Десерты'), ('Первые блюда', 'Первые блюда'), ('Вторые блюда', 'Вторые блюда'), ('Напитки', 'Напитки')], max_length=50)),
            ],
        ),
    ]
