# Generated by Django 5.1.7 on 2025-03-26 20:32

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_add_slug_field'),  # Замените на реальное имя
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.TextField(blank=True, default='', verbose_name='Шаги приготовления'),
        ),
    ]