# Generated by Django 5.1.7 on 2025-03-26 20:34


from django.db import migrations, models
import django.core.validators 

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0003_add_cooking_steps'),  # Замените на реальное имя
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(
                default=30,
                verbose_name="Время приготовления (мин)",
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]