# Generated by Django 5.1.7 on 2025-03-26 20:40


from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_add_cooking_time'),  # Замените на реальное имя
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(
                max_length=50,
                choices=[
                    ('Легко', 'Легко'),
                    ('Средне', 'Средне'), 
                    ('Сложно', 'Сложно'),
                ],
                default='Средне',
                verbose_name="Сложность"
            ),
        ),
    ]