# Generated by Django 5.1.7 on 2025-03-26 20:42


from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_add_difficulty_field'),  # Замените на реальное имя
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                upload_to='recipes/',
                blank=True,
                null=True,
                verbose_name="Изображение"
            ),
        ),
    ]