# Generated by Django 5.1.7 on 2025-03-26 20:45

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('recipes', '0006_add_image_field'),
#     ]

#     operations = [
#     ]
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),  # Укажите правильную зависимость
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name="Дата обновления"
            ),
        ),
    ]