# Generated by Django 5.1.7 on 2025-03-26 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_add_image_field'),
        ('recipes', '0007_add_created_at'),
    ]

    operations = [
    ]
